"""Qwen-Image inference helpers with optional IP-Adapter fallback handling."""

from __future__ import annotations

import argparse
import inspect
import os
import zlib
from pathlib import Path
from typing import Any

from generate_images import draw_placeholder, read_json

_PIPELINE_CACHE: dict[str, Any] = {}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--prompt-payload",
        type=Path,
        required=True,
        help="JSON payload generated by scripts/run_hpc_generation.py.",
    )
    parser.add_argument(
        "--mock",
        action="store_true",
        help="Write a placeholder image instead of calling a real model.",
    )
    return parser.parse_args()


def _dtype_name_to_torch(dtype_name: str) -> Any:
    import torch

    normalized = str(dtype_name).strip().lower()
    mapping = {
        "bfloat16": torch.bfloat16,
        "bf16": torch.bfloat16,
        "float16": torch.float16,
        "fp16": torch.float16,
        "half": torch.float16,
        "float32": torch.float32,
        "fp32": torch.float32,
    }
    if normalized not in mapping:
        raise ValueError(f"Unsupported dtype for Qwen-Image: {dtype_name}")
    return mapping[normalized]


def _visible_cuda_device_count() -> int:
    visible = os.environ.get("CUDA_VISIBLE_DEVICES")
    if visible is not None:
        entries = [item.strip() for item in visible.split(",") if item.strip()]
        return len(entries)

    import torch

    return torch.cuda.device_count()


def _build_max_memory_map(visible_count: int) -> dict[int, str]:
    return {index: "22GiB" for index in range(visible_count)}


def _build_pipeline(payload: dict[str, Any]) -> Any:
    import torch
    from diffusers import DiffusionPipeline

    model_path = payload["model_path"]
    dtype = _dtype_name_to_torch(payload.get("dtype", "bfloat16"))
    device = str(payload.get("device", "cuda"))
    cpu_offload = bool(payload.get("cpu_offload", False))
    visible_cuda_count = _visible_cuda_device_count() if device.startswith("cuda") else 0

    common_kwargs: dict[str, Any] = {
        "pretrained_model_name_or_path": model_path,
        "torch_dtype": dtype,
        "local_files_only": True,
    }

    if device.startswith("cuda") and torch.cuda.is_available():
        if cpu_offload:
            pipeline = DiffusionPipeline.from_pretrained(**common_kwargs)
            if hasattr(pipeline, "enable_model_cpu_offload"):
                pipeline.enable_model_cpu_offload()
            else:
                pipeline = pipeline.to("cuda")
        elif visible_cuda_count > 1:
            common_kwargs["device_map"] = "balanced"
            common_kwargs["max_memory"] = _build_max_memory_map(visible_cuda_count)
            pipeline = DiffusionPipeline.from_pretrained(**common_kwargs)
        else:
            pipeline = DiffusionPipeline.from_pretrained(**common_kwargs)
            pipeline = pipeline.to("cuda")
    else:
        pipeline = DiffusionPipeline.from_pretrained(**common_kwargs)
        pipeline = pipeline.to("cpu")

    if hasattr(pipeline, "set_progress_bar_config"):
        pipeline.set_progress_bar_config(disable=True)
    if hasattr(pipeline, "enable_vae_slicing"):
        pipeline.enable_vae_slicing()
    if hasattr(pipeline, "enable_attention_slicing"):
        pipeline.enable_attention_slicing("max")

    return pipeline


def _pipeline_cache_key(payload: dict[str, Any]) -> str:
    visible_devices = os.environ.get("CUDA_VISIBLE_DEVICES", "")
    ip_config = payload.get("ip_adapter", {})
    return "|".join(
        [
            str(payload.get("model_path", "")),
            str(payload.get("dtype", "")),
            str(payload.get("device", "")),
            str(bool(payload.get("cpu_offload", False))),
            visible_devices,
            str(ip_config.get("enabled", False)),
            str(ip_config.get("model_path", "")),
            str(ip_config.get("image_encoder_path", "")),
        ]
    )


def get_pipeline(payload: dict[str, Any]) -> Any:
    cache_key = _pipeline_cache_key(payload)
    pipeline = _PIPELINE_CACHE.get(cache_key)
    if pipeline is None:
        pipeline = _build_pipeline(payload)
        _PIPELINE_CACHE.clear()
        _PIPELINE_CACHE[cache_key] = pipeline
    return pipeline


def _fallback_or_raise(requested: str, reason: str) -> dict[str, str]:
    if requested == "require_ip_adapter":
        raise RuntimeError(reason)
    return {
        "requested": requested,
        "effective": "prompt_only",
        "message": f"IP-Adapter unavailable; fallback to prompt_only: {reason}",
    }


def _load_reference_image(path_value: str) -> Any:
    from PIL import Image

    return Image.open(path_value).convert("RGB")


def _payload_lora_specs(payload: dict[str, Any]) -> list[dict[str, Any]]:
    specs: list[dict[str, Any]] = []

    style_lora_path = str(payload.get("style_lora_path") or "").strip()
    if style_lora_path:
        specs.append(
            {
                "role": "style",
                "path": style_lora_path,
                "weight_name": str(payload.get("style_lora_weight_name") or "").strip(),
                "scale": float(payload.get("style_lora_scale", 1.0)),
            }
        )

    for item in payload.get("extra_loras", []) or []:
        if not isinstance(item, dict):
            continue
        lora_path = str(item.get("path") or "").strip()
        if not lora_path:
            continue
        specs.append(
            {
                "role": str(item.get("role") or "extra"),
                "path": lora_path,
                "weight_name": str(item.get("weight_name") or "").strip(),
                "scale": float(item.get("scale", 1.0)),
            }
        )
    return specs


def _adapter_name_for_spec(spec: dict[str, Any]) -> str:
    key = "|".join([spec["path"], spec.get("weight_name", ""), spec.get("role", "")])
    return f"adapter_{zlib.crc32(key.encode('utf-8')) & 0xFFFFFFFF:08x}"


def _ensure_named_lora_loaded(pipe: Any, spec: dict[str, Any]) -> str:
    if not Path(spec["path"]).exists():
        raise RuntimeError(f"LoRA path not found: {spec['path']}")
    if not hasattr(pipe, "load_lora_weights"):
        raise RuntimeError("pipeline runtime does not expose load_lora_weights")

    cache_key = "|".join([spec["path"], spec.get("weight_name", "")])
    loaded_cache = getattr(pipe, "_named_lora_cache", {})
    if cache_key in loaded_cache:
        return str(loaded_cache[cache_key])

    adapter_name = _adapter_name_for_spec(spec)
    load_signature = inspect.signature(pipe.load_lora_weights).parameters
    kwargs: dict[str, Any] = {}
    if "weight_name" in load_signature and spec.get("weight_name"):
        kwargs["weight_name"] = spec["weight_name"]
    if "adapter_name" in load_signature:
        kwargs["adapter_name"] = adapter_name
    if "local_files_only" in load_signature:
        kwargs["local_files_only"] = True
    pipe.load_lora_weights(spec["path"], **kwargs)
    loaded_cache[cache_key] = adapter_name
    pipe._named_lora_cache = loaded_cache
    return adapter_name


def _ensure_payload_loras_loaded(pipe: Any, payload: dict[str, Any]) -> None:
    specs = _payload_lora_specs(payload)
    if not specs:
        if getattr(pipe, "_active_lora_key", None) is not None:
            if hasattr(pipe, "disable_lora"):
                pipe.disable_lora()
            elif hasattr(pipe, "set_adapters"):
                try:
                    pipe.set_adapters([], adapter_weights=[])
                except Exception:  # noqa: BLE001
                    pass
            pipe._active_lora_key = None
        return

    adapter_names: list[str] = []
    adapter_weights: list[float] = []
    for spec in specs:
        adapter_names.append(_ensure_named_lora_loaded(pipe, spec))
        adapter_weights.append(float(spec.get("scale", 1.0)))

    active_key = tuple(zip(adapter_names, adapter_weights))
    if getattr(pipe, "_active_lora_key", None) == active_key:
        return

    if len(adapter_names) > 1 and not hasattr(pipe, "set_adapters"):
        raise RuntimeError("multiple LoRA adapters require pipeline.set_adapters() support")

    if hasattr(pipe, "set_adapters"):
        try:
            pipe.set_adapters(adapter_names, adapter_weights=adapter_weights)
        except TypeError:
            pipe.set_adapters(adapter_names, adapter_weights)
    elif len(adapter_names) == 1 and hasattr(pipe, "fuse_lora"):
        pipe.fuse_lora(lora_scale=adapter_weights[0])
    else:
        raise RuntimeError("pipeline runtime cannot activate the requested LoRA adapters")

    pipe._active_lora_key = active_key


def _ensure_ip_adapter_loaded(pipe: Any, payload: dict[str, Any]) -> None:
    ip_config = payload.get("ip_adapter", {})
    cache_key = "|".join(
        [
            str(ip_config.get("model_path", "")),
            str(ip_config.get("image_encoder_path", "")),
            str(ip_config.get("scale", 1.0)),
        ]
    )
    if getattr(pipe, "_style_ip_adapter_cache_key", None) == cache_key:
        return

    if not hasattr(pipe, "load_ip_adapter"):
        raise RuntimeError("pipeline runtime does not expose load_ip_adapter")

    load_signature = inspect.signature(pipe.load_ip_adapter).parameters
    kwargs: dict[str, Any] = {}
    args: list[Any] = [ip_config.get("model_path", "")]

    image_encoder_path = str(ip_config.get("image_encoder_path", "")).strip()
    if "image_encoder_folder" in load_signature and image_encoder_path:
        kwargs["image_encoder_folder"] = image_encoder_path
    elif "image_encoder_path" in load_signature and image_encoder_path:
        kwargs["image_encoder_path"] = image_encoder_path

    pipe.load_ip_adapter(*args, **kwargs)

    if hasattr(pipe, "set_ip_adapter_scale"):
        pipe.set_ip_adapter_scale(float(ip_config.get("scale", 1.0)))
    pipe._style_ip_adapter_cache_key = cache_key


def _resolve_style_backend(pipe: Any, payload: dict[str, Any]) -> dict[str, str]:
    requested = str(payload.get("style_backend_requested", "prompt_only"))
    if requested == "prompt_only":
        return {
            "requested": requested,
            "effective": "prompt_only",
            "message": "Style preset uses prompt_only backend",
        }

    reference_path = str(payload.get("style_reference_image_path") or "").strip()
    if not reference_path:
        return _fallback_or_raise(requested, "missing style_reference_image_path")

    if not Path(reference_path).exists():
        return _fallback_or_raise(
            requested, f"reference image not found: {reference_path}"
        )

    ip_config = payload.get("ip_adapter", {})
    if not ip_config.get("enabled", False):
        return _fallback_or_raise(requested, "ip_adapter.enabled is false")

    model_path = str(ip_config.get("model_path", "")).strip()
    image_encoder_path = str(ip_config.get("image_encoder_path", "")).strip()
    if not model_path:
        return _fallback_or_raise(requested, "ip_adapter.model_path is empty")
    if not Path(model_path).exists():
        return _fallback_or_raise(requested, f"ip_adapter.model_path not found: {model_path}")
    if not image_encoder_path:
        return _fallback_or_raise(requested, "ip_adapter.image_encoder_path is empty")
    if not Path(image_encoder_path).exists():
        return _fallback_or_raise(
            requested,
            f"ip_adapter.image_encoder_path not found: {image_encoder_path}",
        )

    try:
        _ensure_ip_adapter_loaded(pipe, payload)
    except Exception as exc:  # noqa: BLE001
        return _fallback_or_raise(requested, f"unable to load IP-Adapter: {exc}")

    call_signature = inspect.signature(pipe.__call__).parameters
    if "ip_adapter_image" not in call_signature:
        return _fallback_or_raise(
            requested,
            "pipeline call signature does not accept ip_adapter_image",
        )

    return {
        "requested": requested,
        "effective": "ip_adapter",
        "message": "IP-Adapter backend active",
    }


def _build_generation_kwargs(
    pipe: Any,
    payload: dict[str, Any],
    backend_resolution: dict[str, str],
) -> dict[str, Any]:
    import torch

    parameters = inspect.signature(pipe.__call__).parameters
    kwargs: dict[str, Any] = {
        "prompt": payload["prompt"],
        "negative_prompt": payload.get("negative_prompt", ""),
        "width": int(payload["width"]),
        "height": int(payload["height"]),
        "num_inference_steps": int(payload.get("num_inference_steps", 28)),
    }

    scale = float(payload.get("guidance_scale", payload.get("true_cfg_scale", 4.0)))
    if "true_cfg_scale" in parameters:
        kwargs["true_cfg_scale"] = scale
    elif "guidance_scale" in parameters:
        kwargs["guidance_scale"] = scale

    if "generator" in parameters:
        generator_device = "cpu"
        if (
            str(payload.get("device", "cuda")).startswith("cuda")
            and torch.cuda.is_available()
            and not bool(payload.get("cpu_offload", False))
        ):
            generator_device = "cuda"
        kwargs["generator"] = torch.Generator(device=generator_device).manual_seed(
            int(payload["seed"])
        )

    if backend_resolution["effective"] == "ip_adapter":
        kwargs["ip_adapter_image"] = _load_reference_image(
            str(payload["style_reference_image_path"])
        )

    return kwargs


def generate_from_payload(payload: dict[str, Any]) -> dict[str, Any]:
    pipe = get_pipeline(payload)
    _ensure_payload_loras_loaded(pipe, payload)
    output_path = Path(payload["output_path"])
    output_path.parent.mkdir(parents=True, exist_ok=True)

    backend_resolution = _resolve_style_backend(pipe, payload)
    result = pipe(**_build_generation_kwargs(pipe, payload, backend_resolution))
    image = result.images[0]
    image.save(output_path)
    return {
        "output_path": output_path.as_posix(),
        "style_backend_effective": backend_resolution["effective"],
        "style_backend_message": backend_resolution["message"],
    }


def main() -> int:
    args = parse_args()
    payload = read_json(args.prompt_payload)
    output_path = Path(payload["output_path"])
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if args.mock:
        record = {
            "style_id": payload.get("style_id", "unknown"),
            "case_id": payload.get("case_id", "unknown"),
            "scene_id": payload.get("scene_id", "unknown"),
            "candidate_id": payload.get("candidate_id", "unknown"),
            "seed": payload["seed"],
            "prompt": payload["prompt"],
        }
        draw_placeholder(output_path, record, int(payload["width"]), int(payload["height"]))
        return 0

    generate_from_payload(payload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
