"""Qwen-Image inference helpers for Member B generation.

The module can be used in two ways:

1. imported from the generation worker, where the pipeline is cached in-process
   and reused across many records
2. executed as a CLI against a single prompt payload JSON

The implementation is written around the local diffusers-formatted
Qwen-Image-2512 checkpoint under ``/data/home/sim6g/code/DSAA2012``.
"""

from __future__ import annotations

import argparse
import inspect
import os
from pathlib import Path
from typing import Any

from generate_images import draw_placeholder, read_json

_PIPELINE_CACHE: dict[str, Any] = {}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--prompt-payload",
        type=Path,
        required=True,
        help="JSON payload generated by scripts/run_hpc_generation.py.",
    )
    parser.add_argument(
        "--mock",
        action="store_true",
        help="Write a placeholder image instead of calling a real model.",
    )
    return parser.parse_args()


def _dtype_name_to_torch(dtype_name: str) -> Any:
    import torch

    normalized = str(dtype_name).strip().lower()
    mapping = {
        "bfloat16": torch.bfloat16,
        "bf16": torch.bfloat16,
        "float16": torch.float16,
        "fp16": torch.float16,
        "half": torch.float16,
        "float32": torch.float32,
        "fp32": torch.float32,
    }
    if normalized not in mapping:
        raise ValueError(f"Unsupported dtype for Qwen-Image: {dtype_name}")
    return mapping[normalized]


def _visible_cuda_device_count() -> int:
    visible = os.environ.get("CUDA_VISIBLE_DEVICES")
    if visible is not None:
        entries = [item.strip() for item in visible.split(",") if item.strip()]
        return len(entries)

    import torch

    return torch.cuda.device_count()


def _build_max_memory_map(visible_count: int) -> dict[int, str]:
    # Leave headroom for activations and allocator fragmentation on 24 GB cards.
    return {index: "22GiB" for index in range(visible_count)}


def _build_pipeline(payload: dict[str, Any]) -> Any:
    import torch
    from diffusers import DiffusionPipeline

    model_path = payload["model_path"]
    dtype = _dtype_name_to_torch(payload.get("dtype", "bfloat16"))
    device = str(payload.get("device", "cuda"))
    visible_cuda_count = _visible_cuda_device_count() if device.startswith("cuda") else 0

    common_kwargs: dict[str, Any] = {
        "pretrained_model_name_or_path": model_path,
        "torch_dtype": dtype,
        "local_files_only": True,
    }

    if device.startswith("cuda") and torch.cuda.is_available():
        if visible_cuda_count > 1:
            common_kwargs["device_map"] = "balanced"
            common_kwargs["max_memory"] = _build_max_memory_map(visible_cuda_count)
            pipeline = DiffusionPipeline.from_pretrained(**common_kwargs)
        else:
            pipeline = DiffusionPipeline.from_pretrained(**common_kwargs)
            pipeline = pipeline.to("cuda")
    else:
        pipeline = DiffusionPipeline.from_pretrained(**common_kwargs)
        pipeline = pipeline.to("cpu")

    if hasattr(pipeline, "set_progress_bar_config"):
        pipeline.set_progress_bar_config(disable=True)
    if hasattr(pipeline, "enable_vae_slicing"):
        pipeline.enable_vae_slicing()
    if hasattr(pipeline, "enable_attention_slicing"):
        pipeline.enable_attention_slicing("max")

    return pipeline


def _pipeline_cache_key(payload: dict[str, Any]) -> str:
    visible_devices = os.environ.get("CUDA_VISIBLE_DEVICES", "")
    return "|".join(
        [
            str(payload.get("model_path", "")),
            str(payload.get("dtype", "")),
            str(payload.get("device", "")),
            visible_devices,
        ]
    )


def get_pipeline(payload: dict[str, Any]) -> Any:
    cache_key = _pipeline_cache_key(payload)
    pipeline = _PIPELINE_CACHE.get(cache_key)
    if pipeline is None:
        pipeline = _build_pipeline(payload)
        _PIPELINE_CACHE.clear()
        _PIPELINE_CACHE[cache_key] = pipeline
    return pipeline


def _build_generation_kwargs(pipe: Any, payload: dict[str, Any]) -> dict[str, Any]:
    import torch

    parameters = inspect.signature(pipe.__call__).parameters
    kwargs: dict[str, Any] = {
        "prompt": payload["prompt"],
        "negative_prompt": payload.get("negative_prompt", ""),
        "width": int(payload["width"]),
        "height": int(payload["height"]),
        "num_inference_steps": int(payload.get("num_inference_steps", 28)),
    }

    scale = float(payload.get("guidance_scale", payload.get("true_cfg_scale", 4.0)))
    if "true_cfg_scale" in parameters:
        kwargs["true_cfg_scale"] = scale
    elif "guidance_scale" in parameters:
        kwargs["guidance_scale"] = scale

    if "generator" in parameters:
        generator_device = "cpu"
        if str(payload.get("device", "cuda")).startswith("cuda") and torch.cuda.is_available():
            generator_device = "cuda"
        kwargs["generator"] = torch.Generator(device=generator_device).manual_seed(
            int(payload["seed"])
        )

    return kwargs


def generate_from_payload(payload: dict[str, Any]) -> Path:
    pipe = get_pipeline(payload)
    output_path = Path(payload["output_path"])
    output_path.parent.mkdir(parents=True, exist_ok=True)

    result = pipe(**_build_generation_kwargs(pipe, payload))
    image = result.images[0]
    image.save(output_path)
    return output_path


def main() -> int:
    args = parse_args()
    payload = read_json(args.prompt_payload)
    output_path = Path(payload["output_path"])
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if args.mock:
        record = {
            "case_id": payload.get("case_id", "unknown"),
            "scene_id": payload.get("scene_id", "unknown"),
            "candidate_id": payload.get("candidate_id", "unknown"),
            "seed": payload["seed"],
            "prompt": payload["prompt"],
        }
        draw_placeholder(output_path, record, int(payload["width"]), int(payload["height"]))
        return 0

    generate_from_payload(payload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
